require('dotenv').config();

const { fetchPermits } = require('./fetchPermits');
const { sendPostcard } = require('./sendPostcard');

function parseArgs(argv) {
  const args = { send: false, limit: 10, daysBack: 30 };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--send') args.send = true;
    else if (a === '--limit' && argv[i + 1]) args.limit = Number(argv[++i]);
    else if (a === '--days' && argv[i + 1]) args.daysBack = Number(argv[++i]);
  }
  return args;
}

/** Build `to` contact for a test send from POSTGRID_TO_* env vars */
function recipientFromEnv() {
  const line1 = process.env.POSTGRID_TO_ADDRESS_LINE1;
  const postal = process.env.POSTGRID_TO_POSTAL_OR_ZIP;
  if (!line1 || !postal) {
    return null;
  }
  return {
    firstName: process.env.POSTGRID_TO_FIRST_NAME || 'Postcard',
    lastName: process.env.POSTGRID_TO_LAST_NAME || 'Test',
    addressLine1: line1,
    addressLine2: process.env.POSTGRID_TO_ADDRESS_LINE2 || undefined,
    city: process.env.POSTGRID_TO_CITY || 'Calgary',
    provinceOrState: process.env.POSTGRID_TO_PROVINCE || 'AB',
    postalOrZip: postal,
    countryCode: process.env.POSTGRID_TO_COUNTRY || 'CA',
  };
}

function senderFromEnv() {
  const line1 = process.env.POSTGRID_FROM_ADDRESS_LINE1;
  if (!line1) return undefined;
  return {
    firstName: process.env.POSTGRID_FROM_FIRST_NAME || 'Sender',
    lastName: process.env.POSTGRID_FROM_LAST_NAME || '',
    addressLine1: line1,
    addressLine2: process.env.POSTGRID_FROM_ADDRESS_LINE2 || undefined,
    city: process.env.POSTGRID_FROM_CITY,
    provinceOrState: process.env.POSTGRID_FROM_PROVINCE,
    postalOrZip: process.env.POSTGRID_FROM_POSTAL_OR_ZIP,
    countryCode: process.env.POSTGRID_FROM_COUNTRY || 'CA',
  };
}

function permitToHtml(permit) {
  const lines = [
    permit.permitnum && `Permit: ${permit.permitnum}`,
    permit.issueddate && `Issued: ${String(permit.issueddate).slice(0, 10)}`,
    permit.permitclass && `Class: ${permit.permitclass}`,
    permit.originaladdress && `Address: ${permit.originaladdress}`,
    permit.communityname && `Community: ${permit.communityname}`,
  ].filter(Boolean);

  const body = lines.map((l) => `<p style="margin:6px 0;font-size:14px;">${escapeHtml(l)}</p>`).join('');

  const front = `
<!DOCTYPE html><html><body style="margin:0;padding:24px;font-family:Arial,sans-serif;background:#f5f5f5;">
  <h1 style="font-size:20px;color:#333;">Calgary building permit</h1>
  ${body}
</body></html>`;

  const back = `
<!DOCTYPE html><html><body style="margin:0;padding:24px;font-family:Arial,sans-serif;">
  <p style="font-size:12px;color:#555;">Generated by calgary-permit-mailer. Property addresses in open data may be incomplete for mailing.</p>
</body></html>`;

  return { front, back };
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

async function main() {
  const { send, limit, daysBack } = parseArgs(process.argv);

  console.error(`Fetching up to ${limit} permits (issued in last ${daysBack} days)…`);
  const permits = await fetchPermits({ limit, daysBack });
  console.error(`Got ${permits.length} record(s).`);

  if (permits.length) {
    console.log(JSON.stringify(permits.slice(0, 5), null, 2));
    if (permits.length > 5) console.error('(showing first 5 as JSON on stdout)');
  }

  if (!send) {
    console.error('Done (fetch only). Pass --send with POSTGRID_TO_* set to create a postcard.');
    return;
  }

  const to = recipientFromEnv();
  if (!to) {
    console.error(
      'Missing recipient: set POSTGRID_TO_ADDRESS_LINE1 and POSTGRID_TO_POSTAL_OR_ZIP (and optional city/province).',
    );
    process.exitCode = 1;
    return;
  }

  const permit = permits[0];
  if (!permit) {
    console.error('No permits to use for postcard content.');
    process.exitCode = 1;
    return;
  }

  const { front, back } = permitToHtml(permit);
  const from = senderFromEnv();
  const payload = {
    to,
    ...(from ? { from } : {}),
    frontHTML: front,
    backHTML: back,
    size: process.env.POSTGRID_POSTCARD_SIZE || '6x4',
    mailingClass: process.env.POSTGRID_MAILING_CLASS || 'standard_class',
    description: `Permit ${permit.permitnum || 'unknown'}`,
  };

  console.error('Sending postcard…');
  const result = await sendPostcard(payload);
  console.log(JSON.stringify(result, null, 2));
}

main().catch((err) => {
  console.error(err.message || err);
  process.exitCode = 1;
});
